sudo: required
services:
  - docker

before_install:
  - docker build -t jeffwagg/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jeffwagg/docker-react npm run test

deploy:
  provider: elastikbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-795662997303"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"